### ISSUE TITLE
Location 1- The bunker

### ISSUE THREAD

**Issue by GreatOrator** [GreatOrator/FallCraft-Map#1]
Area Description: 
Based off fallout 3 vaults. Needs metal walls, cylinder shaped halls. Each bunk like it’s own studio, with a central commons area (think cafeteria type tables and counters and cooking area)  Place for small farm with artificial lighting. Machine room for making power and purifying water. Bunker door control room and commander’s office.

**Comment by GreatOrator** [comment]
Build Status: Complete
HQM Status: Not Done
CustomNPC Status: Not Done

**Comment by teagan75** [comment]
Build Status: Complete
BQ Status: Done
CustomNPC Status: Done
