### ISSUE TITLE
Location 2- Pleasant Valley

### ISSUE THREAD

**Issue by GreatOrator** [GreatOrator/FallCraft-Map#2]
Area Description: 
Quaint, little all-American town. Along Main Street is the businesses and “downtown” feel. Pre-war businesses are now bartering areas and trade posts. Beat up, worn down streets (almost non-existent) A bunch of small town houses. (think 1950’s) Houses are weathered and worn from the war and 100 years of decay. At the end of Main Street is a beat up town hall where the mayor works and resides. The survivors have built a makeshift wall around their town to try to protect what is left. A few small trees and farms still remain. Self sustaining power (immersive engineering)

**Comment by GreatOrator** [comment]
Build Status: 80% Complete
HQM Status: Not Done
CustomNPC Status: Not Done

**Comment by teagan75** [comment]
Build Status: Complete
BQ Status: Done
CustomNPC Status: Done
