### ISSUE TITLE
Modpack isn't loading properly

### ISSUE THREAD

**Issue by TyHen** [GreatOrator/FallCraft-Map#23]
I have updated to the latest version of Fallcraft. But the problem is that it is not updating. It is stuck on version 0.9.1. I have tried to force update the pack, but it does nothing. Even copying over the files. When I load the pack, the mods load, but I get the decimation mod screen and nothing else. How can this be fixed as I have been looking forward to this since it was first announced by the Squad? Also as a side note, there is no where to download any maps, nor is there any custom splash and main background for me. If you need pictures as proof let me know and I will be glad to screen shot them. Thanks Y'all.

**Comment by TyHen** [comment]
I have re downloaded the instance several times. Still says it is on version 0.9.1, also I update when I see your tweets, but curse never shows them for me, hence the force updating...All other packs including tolkiencraft 3 I see updates for.

**Comment by GreatOrator** [comment]
So for whatever reason it is not completely removing old mods when you update.  In my case it was bibliocraft, so I manually deleted the old version.  As for the version, that is an error with curse.  I verified aside from that mod deleting error it is the correct version, curse is not properly relaying that.

**Comment by TyHen** [comment]
Ok so I just need to find the old mod and delete it. I just did another test and I can load from 0.9.1 to 0.10.5, but 0.11.1 reverts back to 0.9.1. I will let you know what I find. Thank you sir!

**Comment by GreatOrator** [comment]
yeah, that is actually a bug, it is in fact the new version but curse tagged it at 9.1

**Comment by TyHen** [comment]
Ok so I have deleted bibliocraft and got an error for bibliowoods, deleted that as well. And I still have the same problem of when the modpack loads and loads in the decimation mod screen.

**Comment by GreatOrator** [comment]
I uploaded a new version to curse, try that once it shows available and let me know

**Comment by TyHen** [comment]
It has worked and curse has updated the correct file as well. Thank you so much and thanks for the awesome modpacks!

**Comment by GreatOrator** [comment]
Perfect!  Glad we got it worked out so quickly.
