### ISSUE TITLE
Better Questing Book in edit mode

### ISSUE THREAD

**Issue by Ladysarajane** [GreatOrator/FallCraft-Map#25]
Started the map and realized that Better Questing was left in edit mode.

Also a question, I talked to Ethel and she supposedly gave me a baseball bat....I didn't receive anything. Found the Weapons locker and I assume the pistol for George is in the chest....How do I open it?

**Comment by teagan75** [comment]
We are having some major technical issues :( It would be best to wait for an update

**Comment by Ladysarajane** [comment]
Okay....I thought I was going crazy there for a moment....LOL

**Comment by Ladysarajane** [comment]
Nope NOT working. The bq quest book looks awesome now, but the NPC quest log is not triggering, it doesn't have any quests for me to to. Ethel will not talk about trouble with her water or power in her room. Just asks me what I am doing.  I did download a new instance 0.11.11 and the new map Colorado

**Comment by teagan75** [comment]
If you know how to open your save file and then the world file, inside there is a customnpc folder. Is there anything inside? Wondering if the file isn’t downloading properly

**Comment by Ladysarajane** [comment]
Yes there are several files in my saves/world/customnpc folder. I mean the NPC Ethel talks to me....just doesn't trigger the options to start the quest.  Is there a specific file in that folder I should look for?

**Comment by teagan75** [comment]
Not every npc gives an official quest. If you finished her conversation BQ tells you where to go next and it should work. Unless something else messes up, or if the direction given in the quest book isn’t working, just follow it.

**Comment by Ladysarajane** [comment]
BQ tells me to go to George. George only says hello to me and doesnt complete. In the previous map Ethel complained about her water and power in her room and I went back and forth and Ethel was suppose to give me a bat, then George sends me to the commander then after tells me to find his pistol. I get none of that. Ethel only gives me the one choice and completes that portion of Better Questing,(Ethel) but I can't complete George portion.

**Comment by teagan75** [comment]
When you talk to Ethel she says her intro and then you click on your response. Does the conversation close after that? Trying to see if your getting that bug

**Comment by Ladysarajane** [comment]
Yes that is what happens!
She says, "Hello there, seems like a life time since I've seen you. Where are you off to?" And the only option is to pick to say is "Nowhere, just trying to find something to pass the time" and when I click that it closes  after that.  If I click Ethel again, we repeat the same conversation.

**Comment by teagan75** [comment]
That shouldn’t be happening ☹️ And I have no idea what is going on with that. I need to test the file again. 

Out of curiosity, do you play on a Mac? There is a bug with the map dl and Macs. Later today I plan to put the map on Curse as an extra file to dl

**Comment by Ladysarajane** [comment]
No, I play on a PC.
Seems like a similar problem with NPC quests like you had in witchery and downloads.
 In the previous map, it was fine in convos, but I didn't receive the bat from Ethel and I couldn't open the weapons locker to get the pistol of Georges

**Comment by teagan75** [comment]
Somehow Ethel's second dialogue went MIA D: not sure how that happened but will be fixed for next update

**Comment by Ladysarajane** [comment]
Okay. I will try it again when next update is out. Thanks Teagan!

**Comment by Ladysarajane** [comment]
Just got the update and these issues are resolved. Totally loving the NPC'S in Pleasant Valley. 🤣
