### ISSUE TITLE
Beta 0.12.5 NPC  Mayor Pepper and the abandoned Mine

### ISSUE THREAD

**Issue by Ladysarajane** [GreatOrator/FallCraft-Map#29]
This might be my dumbness, But after talking to Mayor Pepper to negotiate the truce, she gives me a campfire and then I am at a lost on what to do. I talk to her again and repeats her last convo. I talk to the abandoned mine people and I repeat the convo's. I tried taking the dolls to it's owner and nothing. Do I return the stolen items? I can't figure out what to do next.

**Comment by teagan75** [comment]
That is basically the ending of that quest. I need to add a tutorial on how to use the campfire in the quest book. 

Do you think it would be more closure if you had to return the items?

**Comment by Ladysarajane** [comment]
I do. I hate to see Modii without his items (((lol)) and it would give closure to that line. The dolls and rocking chair aren't a problem, but roscoe the dog would be. Can't pick him up.

**Comment by teagan75** [comment]
In multiplayer, players can’t break or place blocks except for a few items. So I would need to make invisible npcs near the dolls and rocking chair to give the items.

**Comment by teagan75** [comment]
This is now added for the next update.
