### ISSUE TITLE
Location 3- Cozyton

### ISSUE THREAD

**Issue by GreatOrator** [GreatOrator/FallCraft-Map#3]
Area Description: 
Small makeshift town made out of an old summer camp. 4 log cabins with 6 to 8 beds each. A fire pit in the middle with a few logs around for seating. A large common room/cafeteria. In the cafeteria there is a locked walk in freezer that is always guarded. Some creepy items around, like a bunch of dolls in the corner of the room etc.

**Comment by GreatOrator** [comment]
Build Status: Complete
HQM Status: Not Done
CustomNPC Status: Not Done

**Comment by teagan75** [comment]
Build Status: Complete
BQ Status: Done
CustomNPC Status: Done
