### ISSUE TITLE
Missing mods error

### ISSUE THREAD

**Issue by R3kandH4V0k** [GreatOrator/FallCraft-Map#34]
Hi I just downloaded the pack and the custom map, but when I wemt to start it I had this pop up. Is it OK to continue??[
![jpeg_20180914_194153](https://user-images.githubusercontent.com/26939945/45579565-987fa300-b856-11e8-881d-d036af1458ae.jpg)
](url)

**Comment by GreatOrator** [comment]
What version number of the pack did you download?  We have been seeing curse forcing an earlier version despite selecting the most recent (which should be 0.14.x)

**Comment by R3kandH4V0k** [comment]
Oh I see it downloaded 0.9.1

**Comment by GreatOrator** [comment]
Yeah, what I thought.  Curse being curse again.  If you still have problems after getting the launcher to let you have the right version, hit me up again 🗡
