### ISSUE TITLE
Location 4- Riverside 

### ISSUE THREAD

**Issue by GreatOrator** [GreatOrator/FallCraft-Map#4]
Area Description: 
A small town that is on a large river. Was a pre war fishing town. Docks on both sides of the river on different levels. All houses/shops are along the docks on the non river side.Suspension Bridges going across the river from dock to dock. Most the houses are small and basic. Lots of barrels around.

**Comment by GreatOrator** [comment]
Build Status: Complete
HQM Status: Not Done
CustomNPC Status: Not Done

**Comment by teagan75** [comment]
Build Status: Complete
BQ Status: Done
CustomNPC Status: Done
