### ISSUE TITLE
Location 5- Littleton 

### ISSUE THREAD

**Issue by GreatOrator** [GreatOrator/FallCraft-Map#5]
Area Description:
Small town like Pleasant Valley but smaller and unprotected. Houses are barricaded instead of a large wall around the whole town. No actual business buildings, just 8 homes. No vegetation, No farms, trees no animals. Small shops inside the people’s homes. Entire town surrounded by lots of rubble.

**Comment by GreatOrator** [comment]
Build Status: Bunker - 20% Complete
HQM Status: Not Done
CustomNPC Status: Not Done

**Comment by teagan75** [comment]
Build Status: Complete
BQ Status: Done
CustomNPC Status: Done
