### ISSUE TITLE
Location 6- Miner’s Den

### ISSUE THREAD

**Issue by GreatOrator** [GreatOrator/FallCraft-Map#6]
Area Description: 
Shanty town built next to a mining cave in a mountain. Wild west gold rush run down town. The mining cave opens up to a large hole in the ground. Broken staircase leads the way down and it is very dim. At the bottom it opens into 3 main shafts. Logs bracing the walls and ceilings. Lamps and redstone lighting. One tunnel is short and the end has been collapsed. Other two tunnels branch out. Both lead to a large cavern room. Lots of webbing and activity of spiders. Webs everywhere. From there, there is a natural looking tunnel that looks like it has been blasted open that leads to a huge spider den.

**Comment by teagan75** [comment]
Build Status: Complete
BQ Status: Done
CustomNPC Status: Done
