### ISSUE TITLE
Location 7- Da Kamp (Black Forest Observatory) 

### ISSUE THREAD

**Issue by GreatOrator** [GreatOrator/FallCraft-Map#7]
Area Description: 
Big, white observatory on the top of a mountain. 4 floors. First three floors like normal floors. fourth floor a big dome roof with telescope in it. Chain link fence around area. 3 satellite dishes. First floor has cafeteria and weapons depot. second floor barrack type sleeping area. third floor science lab.

**Comment by GreatOrator** [comment]
Build Status: Complete
HQM Status: Not Done
CustomNPC Status: Not Done

**Comment by teagan75** [comment]
Build Status: Complete
BQ Status: Done
CustomNPC Status: Done
