### ISSUE TITLE
Location 8- Skaguay Dam

### ISSUE THREAD

**Issue by GreatOrator** [GreatOrator/FallCraft-Map#8]
Area Description: 
Large Dam between two mountains. Concrete. Large lake behind it. Deep cavern in front of it with small river. Multiple floors. Entrance on top in a visitor’s center. Each floor is dark, gloomy and drippy. Lots of turbines and other non-working machinery. Multiple rooms for exploring. Lots of vines. 
First floor is mainly offices.

**Comment by GreatOrator** [comment]
I'll edit the initial comment with the coordinates later today.  Dam has been started and currently has support for 7 floors.  Working on stair wells and the plan is to have identical "towers" on each side and every other floor is blocked off forcing players to transverse each and every floor to make it to the bottom.  At current, may have to raise dam height a little more to accommodate the full 8 floors we want.  Will further test later today as well.

**Comment by GreatOrator** [comment]
Build Status: Complete
HQM Status: Not Done
CustomNPC Status: Not Done

**Comment by teagan75** [comment]
Build Status: Complete
BQ Status: Done
CustomNPC Status: Done
